### ISSUE TITLE
zos command hangs at creating a contract and calling a function: zos 2.4-

### ISSUE THREAD

**Issue by crazyrabbitLTC** [zeppelinos/zos#1027]
I am suspecting this is either related to: [issue #1025 ](https://github.com/zeppelinos/zos/issues/1025) or it's something happening on my machine in particular. 

When using the `zos create counter` on the zepkit tutorial (created via `zos unpack tutorial`) when it prompts me to choose if I want to run a function it the terminal window freezes. 

<img width="553" alt="Screen Shot 2019-06-20 at 4 21 17 PM" src="https://user-images.githubusercontent.com/1938013/59878929-87c90400-9377-11e9-8871-eca4eb8d11ef.png">

In trying to figure out if it's related to my machine, I try running `npx zos --version` in the same directory, but in a different terminal window to try and figure out if there is some sort of conflict. 

The result is: 

```
 dennison@Dennisons-MacBook-Pro  ~/Documents/kittest  npx zos --version
Cannot run more than one instance of 'zos' at the same time.
If you are sure that no other instances are actually running, manually remove the file .zos.lock and try again.
```

Not sure if that helps in debugging or not.

**Comment by spalladino** [comment]
@crazyrabbitLTC this is probably caused by a faulty release in `inquirer.js` (see https://github.com/SBoudrias/Inquirer.js/issues/812 and https://github.com/SBoudrias/Inquirer.js/issues/811). There was a new release fixing this literally 6 hours ago. Can you try reinstalling `zos`, which should download the latest version of inquirer with the fix?
