### ISSUE TITLE
ERR! fatal: could not create leading directories

### ISSUE THREAD

**Issue by thecircleoflifefree** [zeppelinos/zos#1082]
[root@iec2-user]# npm install --global zos
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b browserifyCompatible git://github.com/frozeman/WebSocket-Node.git /root/.npm/_cacache/tmp/git-clone-c9085df7
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-c9085df7': Permission denied
npm ERR!

################
[root@ec2-user]# uname -v
#1 SMP Fri Jun 14 13:20:24 UTC 2019
[root@ec2-user]# node -v
v10.14.1
[root@ec2-user]# npm -v
6.10.0

**Comment by abcoathup** [comment]
This appears to be a node/npm permission issue.

If you are not already, you could use node/npm with a node version manager, otherwise you could install zos locally (rather than globally) and use via npx.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Please note if changing node versions, there is an issue using node 12 (https://forum.zeppelin.solutions/t/node-12-issue-with-truffle/808) so you need to use either node 10 or 11.

For questions regards ZeppelinOS you can ask in the community forum: https://forum.zeppelin.solutions/

**Comment by jcarpanelli** [comment]
Hey @thecircleoflifefree, as @abcoathup said, this is probably a node/npm permission issue. I'm closing it for now, but feel free to write your comments here and we'll answer you :slightly_smiling_face:.

**Comment by gorgos** [comment]
Solution is https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/54#issuecomment-422588462 btw.

**Comment by abcoathup** [comment]
Hi @gorgos,

If you use a node version manager as per one of the recommended options in npm docs (https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) then you shouldn't need to use `sudo`.

My understanding is that best practice is not to use `sudo` with `npm`

**Comment by chinggoy** [comment]
use "sudo npm install"  instead.. this will solve your problem

**Comment by abcoathup** [comment]
Hi @chinggoy,

I discourage use of sudo with npm so recommend either of the solutions proposed by npm (I personally use nvm) 
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
