### ISSUE TITLE
Test upgrade path for ZepToken from TPL to PausableToken

### ISSUE THREAD

**Issue by fiiiu** [zeppelinos/zos#129]
As described in #121, we cannot extend from both `TPLToken` and `PausableToken`. The _pausable_ functionality is present in TPL through the removal of attributes, but we wanted `pausable` for when we drop TPL in the future. We are now keeping TPL and dropping `PausableToken`, but we need to thoroughly test that the upgrade path from TPL to pausable works fine.

**Comment by spalladino** [comment]
@facuspagnuolo @fiiiu I don't think this strategy would work, as the problem with linearization is not caused by TPLToken and PausableToken, but by DetailedPremintedToken and PausableToken. So we would not even be able to set up a PausableToken without hitting this issue. I'll review this with @frangio to see how we handle it. For now, I wouldn't move forward with this.

**Comment by spalladino** [comment]
See https://github.com/OpenZeppelin/openzeppelin-zos/issues/17

**Comment by fiiiu** [comment]
Whoops, true dat, thanks for catching @spalladino! I'm closing this and reopening #121 with an improved description.
