### ISSUE TITLE
Transactions fail when using proxy contracts deployed with zos

### ISSUE THREAD

**Issue by miguelmota** [zeppelinos/zos#809]
Sending transactions to a proxy contract or even the backing logic contract fails when deployed with zepellingOS, but sending transactions to a contract deployed with just web3 work. I don't know how or why so here's a repo with the reproducible bug and instructions on running.

https://github.com/miguelmota/zos-bug-example

The particular method invocation example where it's throwing a revert is [here](https://github.com/miguelmota/zos-bug-example/blob/master/scripts/debug.js). 

It seems to fail when trying to set storage. Nothing fails, and it works when NOT using zOS.
Any help is appreciated, thanks.

**Comment by spalladino** [comment]
Hey @miguelmota! Thanks a lot for the detailed example, it helps a lot in troubleshooting the issue. The problem seems to lie not in ZeppelinOS but in Ganache, in particular regarding gas estimation or processing. 

Adding a high gas allowance to the `instance.submitTransaction` call makes the transaction go through without issues. Also, switching to geth in devmode (`geth --dev  --datadir=.geth --rpc --rpcport=9545`) works without any changes to the code, since gas estimation and processing in geth work correctly.

It'd be great to come up with an even-more-minimal example of this issue for the ganache team, so we can create a detailed issue in case someone else runs into this.

**Comment by spalladino** [comment]
Let me know if the changes to the script (or using geth instead of ganache) work for you so we can close this issue.

**Comment by miguelmota** [comment]
@spalladino oh cool, yea that does the trick! agree that it'd be good if ganache gave a warning of any sort. Thanks again
