### ISSUE TITLE
`admin` state variable should not be allowed

### ISSUE THREAD

**Issue by jchittoda** [zeppelinos/zos#852]
In the implementation contract one can add state variables, however if the state variable is defined like 
```
address public admin;
```
It will not be fetched from `AdminUpgradeabilityProxy` instance. Because there is already a function `admin()` defined like below:
```
  function admin() external view ifAdmin returns (address) {
    return _admin();
  }
```

With `zos` command during the `zos push`, it should warn the user to change the name of the state variable and not to use `admin` as any of the state variable name.

**Comment by spalladino** [comment]
Hey @jchittoda! Thanks for reporting that. However, this is not an issue with `zos` proxies, since we are following the [transparent proxy pattern](https://docs.zeppelinos.org/docs/pattern.html#transparent-proxies-and-function-clashes). This means that, if a logic contract has a method that clashes with one of the proxy (such as `admin` or `upgradeTo`), it will only be callable by a user, but not from its admin (and viceversa).

**Comment by chenqping** [comment]
I got nothing when calling admin() from proxy contract instance on Remix, anybody know why?

**Comment by abcoathup** [comment]
Hi @chenqping,

I see that you have created an Issue on this: https://github.com/OpenZeppelin/openzeppelin-sdk/issues/1501
We can pick up the discussion there.
