### ISSUE TITLE
Assess and redesign CLI outputs

### ISSUE THREAD

**Issue by spalladino** [zeppelinos/zos#857]
Review the CLI and its outputs (both the prompts and the results of executing each action), and redesign them.

**Comment by jcarpanelli** [comment]
## Delightful DX: Improving the cli's output

### Where do we stand?
At this moment, the cli has 2 different levels of verbosity: The default one (i.e., when not specifying the `--verbose` flag) and the `verbose` mode. The only difference between both is that in `verbose` mode the cli will prepend a string reference to the file that is printing the log and it also will print the stack trace if an error isucesss thrown.

### What should we do?  Improve the current logging!
#### For both modes:

- Instead of adding new levels of verbosity (`--info`, `--warn`, etc) The idea will be to keep these two as they are, but improve them to the point that the default verbosity mode does not log everything, but only the necessary messages that the user would be interested in reading.
- Wording will be reviewed to give the developer the feeling that everything was written by the same person/team following the same narrative style.

#### Verbose logging:
- The idea is to keep the verbose mode as it is, but we are going to prepend the raw file name to the log message and the function that is logging it, instead of just prepending a reference to the file. Expect something like:

`[models/network/NetworkController.ts#doSomething] Doing something...`

#### Non-verbose logging:
- Remove all unnecessary logs in non-verbose mode and merge the ones that can be merged. 
- Stop printing stdouts when using the cli, as they add noise and redundant information that has already been logged in prior messages.
- Change colors: ATM, the tool is printing both success and neutral messages in green, which could be somewhat confusing. Instead, we will use white for neutral messages, green for success messages and red for errors.
- Nice to have: Use a multispinner! The idea would be to use a multispinner which will allow us to give a better understanding of what's happening in each command, as well as merge messages that describe different stages of the same task into only one message, for example:
`Deploying contract Foo...`
`Contract Foo successfully deployed`

**Comment by spalladino** [comment]
Sounds like a good plan @jcarpanelli!! A few questions:

> Stop printing stdouts when using the cli, as they add noise and redundant information that has already been logged in prior messages.
This affects composability of `zos` in scripts or the console, such as being able to run `MYCONTRACT=$(zos create MyContract)`. We should maintain stdout output somehow.

> Change colors
Thank you!!

> Use a multispinner
How would this work in non-interactive environments, such as the log of a CI?

**Comment by jcarpanelli** [comment]
> This affects composability of zos in scripts or the console, such as being able to run MYCONTRACT=$(zos create MyContract). We should maintain stdout output somehow.

I believe that a valid approach would be to add an additional flag (such as `--stdout`) for those cases. WDYT?

> How would this work in non-interactive environments, such as the log of a CI?

Don't worry, the multispinner I'm working on (I implemented it some weeks ago and should take some time to finish it) checks whether `process.env.CI` and `process.stderr.isTTY` are true or not and should enable/disable the spinners as appropiate (ie, will print the messages without spinning)

**Comment by spalladino** [comment]
Awesome! Maybe we could also use the `isTTY` for deciding whether to output to `stdout`? Anyway, as long as we make sure to keep that working somehow, I'm good!

**Comment by spalladino** [comment]
Implemented by @jcarpanelli!
